version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./files/app/
      dockerfile: Dockerfile
    environment:
       DB_NAME: "testdb"
       DB_USER: "testuser"
       DB_PASSWORD: "testpass"
       DB_PORT: "5432"
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
      - /etc/nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"
    depends_on:
      - app
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}
